name: test_rm_api
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  rick_and_morty_api:
    git:
      url: git@github.com:Yash-Garg/RickandMorty-Dart-Wrapper.git
  auto_route: 5.0.1
  salomon_bottom_bar: ^3.3.1
  mobx: ^2.0.6
  flutter_mobx: ^2.0.6+1
  validators2: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^5.0.2
  build_runner: ^2.2.1
  mobx_codegen: ^2.0.7

flutter:
  uses-material-design: true
